// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: create_order.sql

package orm

import (
	"context"
	"database/sql"
	"time"
)

const createDeliveryInfo = `-- name: CreateDeliveryInfo :exec
INSERT INTO delivery_info (order_id, name, address, phone, message)
VALUES (?, ?, ?, ?, ?)
`

type CreateDeliveryInfoParams struct {
	OrderID int64
	Name    string
	Address string
	Phone   string
	Message sql.NullString
}

func (q *Queries) CreateDeliveryInfo(ctx context.Context, arg CreateDeliveryInfoParams) error {
	_, err := q.db.ExecContext(ctx, createDeliveryInfo,
		arg.OrderID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Message,
	)
	return err
}

const createOrderInfo = `-- name: CreateOrderInfo :execresult
INSERT INTO ` + "`" + `order` + "`" + ` (user_id, price, deposit, discount, reservated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateOrderInfoParams struct {
	UserID       int64
	Price        int32
	Deposit      int32
	Discount     int32
	ReservatedAt time.Time
}

func (q *Queries) CreateOrderInfo(ctx context.Context, arg CreateOrderInfoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderInfo,
		arg.UserID,
		arg.Price,
		arg.Deposit,
		arg.Discount,
		arg.ReservatedAt,
	)
}

const createOrderState = `-- name: CreateOrderState :exec
INSERT INTO order_state (order_id)
VALUES (?)
`

func (q *Queries) CreateOrderState(ctx context.Context, orderID int64) error {
	_, err := q.db.ExecContext(ctx, createOrderState, orderID)
	return err
}

const createOrderedDinner = `-- name: CreateOrderedDinner :execresult
INSERT INTO ordered_dinner (order_id, style_id, amount)
VALUES (?, ?, ?)
`

type CreateOrderedDinnerParams struct {
	OrderID int64
	StyleID int32
	Amount  int32
}

func (q *Queries) CreateOrderedDinner(ctx context.Context, arg CreateOrderedDinnerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderedDinner, arg.OrderID, arg.StyleID, arg.Amount)
}

const createOrderedMenu = `-- name: CreateOrderedMenu :exec
INSERT INTO ordered_menu (order_id, dinner_id, menutype_id, menu_id, option1_id, option2_id, count, price)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderedMenuParams struct {
	OrderID    int64
	DinnerID   int64
	MenutypeID int32
	MenuID     int32
	Option1ID  int32
	Option2ID  int32
	Count      int32
	Price      sql.NullInt32
}

func (q *Queries) CreateOrderedMenu(ctx context.Context, arg CreateOrderedMenuParams) error {
	_, err := q.db.ExecContext(ctx, createOrderedMenu,
		arg.OrderID,
		arg.DinnerID,
		arg.MenutypeID,
		arg.MenuID,
		arg.Option1ID,
		arg.Option2ID,
		arg.Count,
		arg.Price,
	)
	return err
}
