// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: order.sql

package orm

import (
	"context"
)

const updateOrderState = `-- name: UpdateOrderState :exec
UPDATE order_state
SET state_id = (
SELECT state_id
FROM state
WHERE name = (?))
WHERE order_id = (?)
`

type UpdateOrderStateParams struct {
	Name    string
	OrderID int64
}

func (q *Queries) UpdateOrderState(ctx context.Context, arg UpdateOrderStateParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderState, arg.Name, arg.OrderID)
	return err
}
