// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: staff.sql

package orm

import (
	"context"
)

const getStaffRole = `-- name: GetStaffRole :one
SELECT tag
FROM role, staff
WHERE staff.staff_id = (?)
AND role.role_id = staff.role_id
`

func (q *Queries) GetStaffRole(ctx context.Context, staffID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getStaffRole, staffID)
	var tag string
	err := row.Scan(&tag)
	return tag, err
}
