// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: stock.sql

package orm

import (
	"context"
	"database/sql"
)

const addStockItem = `-- name: AddStockItem :execresult
INSERT INTO stock (name, unit)
VALUES (?, ?)
`

type AddStockItemParams struct {
	Name string
	Unit string
}

func (q *Queries) AddStockItem(ctx context.Context, arg AddStockItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addStockItem, arg.Name, arg.Unit)
}

const deleteStockItem = `-- name: DeleteStockItem :exec
DELETE FROM stock
WHERE stock_id = (?)
`

func (q *Queries) DeleteStockItem(ctx context.Context, stockID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStockItem, stockID)
	return err
}

const getAllStockList = `-- name: GetAllStockList :many
SELECT stock_id, name, count, unit
FROM stock
`

type GetAllStockListRow struct {
	StockID int64
	Name    string
	Count   int32
	Unit    string
}

func (q *Queries) GetAllStockList(ctx context.Context) ([]GetAllStockListRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllStockList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllStockListRow
	for rows.Next() {
		var i GetAllStockListRow
		if err := rows.Scan(
			&i.StockID,
			&i.Name,
			&i.Count,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockItem = `-- name: UpdateStockItem :exec
UPDATE stock
SET count = (?)
WHERE stock_id = (?)
`

type UpdateStockItemParams struct {
	Count   int32
	StockID int64
}

func (q *Queries) UpdateStockItem(ctx context.Context, arg UpdateStockItemParams) error {
	_, err := q.db.ExecContext(ctx, updateStockItem, arg.Count, arg.StockID)
	return err
}
